// GENERATED by scripts/sync-shared.mjs from frontend/src/lib/dashboard-rules.ts. Do not edit here.
/**
 * Shared dashboard calculations. The React demo and Express API use the same
 * scoping and stock-alert definitions, so selecting a godown cannot leave KPI
 * cards or pipeline figures on organisation-wide totals.
 */
import type { Dashboard, Item, SalesOrder, StockAlert } from "./types.js";

type NamedGodown = { id: string; name: string };

export function dashboardInventory(
  items: Item[],
  godowns: NamedGodown[],
  scope: string,
  alerts: StockAlert[],
): Pick<Dashboard, "stockValue" | "lowStock" | "outOfStock" | "nearExpiry" | "overAged" | "valueByGodown"> {
  const scoped = godowns.filter((g) => scope === "all" || g.id === scope);
  const ids = new Set(scoped.map((g) => g.id));
  const totals = new Map(scoped.map((g) => [g.id, 0]));

  for (const item of items) {
    for (const stock of item.stock) {
      if (!ids.has(stock.godownId)) continue;
      totals.set(stock.godownId, (totals.get(stock.godownId) ?? 0) + stock.onHand * item.costPrice);
    }
  }

  const valueByGodown = scoped.map((g) => ({ godownId: g.id, name: g.name, value: Math.round(totals.get(g.id) ?? 0) }));
  const inScope = alerts.filter((a) => ids.has(a.godownId));
  return {
    stockValue: Math.round([...totals.values()].reduce((total, value) => total + value, 0)),
    valueByGodown,
    // KPI counts use *free* stock (on hand minus held), matching the Alerts page.
    lowStock: inScope.filter((a) => a.kind === "below_reorder").length,
    outOfStock: inScope.filter((a) => a.kind === "out_of_stock").length,
    nearExpiry: inScope.filter((a) => a.kind === "near_expiry").length,
    overAged: inScope.filter((a) => a.kind === "over_aged").length,
  };
}

export function dashboardPipeline(orders: SalesOrder[], scope: string): Dashboard["pipeline"] {
  const scoped = orders.filter((order) => scope === "all" || order.godownId === scope);
  const stage = (name: string, statuses: SalesOrder["status"][]) => {
    const selected = scoped.filter((order) => statuses.includes(order.status));
    return { stage: name, count: selected.length, value: selected.reduce((total, order) => total + order.grandTotal, 0) };
  };
  return [
    stage("Draft", ["draft"]),
    stage("Confirmed", ["confirmed"]),
    stage("Part delivered", ["partially_delivered"]),
    stage("Delivered", ["delivered"]),
  ];
}

/**
 * The ledger persists UTC datetimes without a timezone marker. Dashboard days
 * are India business days, so filter using UTC instants at the IST boundaries
 * (18:30 UTC on the preceding calendar date). India has no daylight saving.
 */
export function indiaBusinessDayBoundsUtc(ymd: string) {
  const midnight = Date.parse(`${ymd}T00:00:00+05:30`);
  if (!Number.isFinite(midnight)) throw new Error("Invalid business date");
  const sqlTime = (ms: number) => new Date(ms).toISOString().slice(0, 19).replace("T", " ");
  const dayMs = 86_400_000;
  return {
    todayStart: sqlTime(midnight),
    tomorrowStart: sqlTime(midnight + dayMs),
    lastSevenDaysStart: sqlTime(midnight - 6 * dayMs),
  };
}

/** UTC `DATETIME` column → India-local business date (YYYY-MM-DD). */
export function indiaDateOfUtcSqlTimestamp(value: string): string {
  const utc = Date.parse(value.replace(" ", "T") + "Z");
  if (!Number.isFinite(utc)) throw new Error("Invalid ledger timestamp");
  return new Date(utc + 330 * 60_000).toISOString().slice(0, 10);
}
