// GENERATED by scripts/sync-shared.mjs from frontend/src/lib/gst.ts. Do not edit here.
export type SupplyType = "intra" | "inter";

export interface TaxLineInput {
  qty: number;
  rate: number;
  discountPct: number;
  gstRate: number;
}

export interface TaxTotals {
  taxable: number;
  cgst: number;
  sgst: number;
  igst: number;
  roundOff: number;
  grandTotal: number;
  byRate: { rate: number; taxable: number; tax: number }[];
}

const r2 = (n: number) => Math.round(n * 100) / 100;

/** Same state code (first 2 GSTIN digits) → CGST+SGST, otherwise IGST. */
export function supplyType(orgStateCode: string, placeOfSupplyCode: string): SupplyType {
  return orgStateCode === placeOfSupplyCode ? "intra" : "inter";
}

export function lineTaxable(l: TaxLineInput): number {
  return r2(l.qty * l.rate * (1 - (l.discountPct || 0) / 100));
}

export function computeTotals(lines: TaxLineInput[], type: SupplyType): TaxTotals {
  const map = new Map<number, { taxable: number; tax: number }>();
  let taxable = 0;
  let tax = 0;
  for (const l of lines) {
    const t = lineTaxable(l);
    const x = r2((t * l.gstRate) / 100);
    taxable += t;
    tax += x;
    const e = map.get(l.gstRate) ?? { taxable: 0, tax: 0 };
    e.taxable = r2(e.taxable + t);
    e.tax = r2(e.tax + x);
    map.set(l.gstRate, e);
  }
  taxable = r2(taxable);
  tax = r2(tax);
  const cgst = type === "intra" ? r2(tax / 2) : 0;
  const sgst = type === "intra" ? r2(tax - cgst) : 0;
  const igst = type === "inter" ? tax : 0;
  const exact = r2(taxable + tax);
  const grandTotal = Math.round(exact);
  return {
    taxable,
    cgst,
    sgst,
    igst,
    roundOff: r2(grandTotal - exact),
    grandTotal,
    byRate: [...map.entries()].sort((a, b) => a[0] - b[0]).map(([rate, v]) => ({ rate, ...v })),
  };
}

export interface CreditCheck {
  limit: number;
  outstanding: number;
  orderTotal: number;
  available: number;
  exceeds: boolean;
}

export function creditCheck(limit: number, outstanding: number, orderTotal: number): CreditCheck {
  const available = r2(limit - outstanding);
  return { limit, outstanding, orderTotal, available, exceeds: limit > 0 && orderTotal > available };
}

/** Only an Owner can override a credit-limit block. */
export function canOverrideCredit(role: string): boolean {
  return role === "Owner";
}

/** E-way bill is mandatory when consignment value exceeds ₹50,000. */
export function ewayBillRequired(value: number): boolean {
  return value > 50000;
}

const GSTIN_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

/** Mod-36 check character for the first 14 GSTIN characters. */
export function gstinCheckChar(first14: string): string {
  let sum = 0;
  for (let i = 0; i < 14; i++) {
    const p = GSTIN_CHARS.indexOf(first14[i]!.toUpperCase()) * (i % 2 === 0 ? 1 : 2);
    sum += Math.floor(p / 36) + (p % 36);
  }
  return GSTIN_CHARS[(36 - (sum % 36)) % 36]!;
}

/** Format (2-digit state, PAN, entity, Z, check) plus checksum. */
export function isValidGstin(gstin: string): boolean {
  const g = gstin.trim().toUpperCase();
  if (!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(g)) return false;
  return gstinCheckChar(g.slice(0, 14)) === g[14];
}

/** GSTIN digits 1-2 are the state code. */
export function stateFromGstin(gstin: string): string {
  return gstin.trim().slice(0, 2);
}

export const GST_RATES = [0, 5, 12, 18, 28] as const;
export const HSN_PATTERN = /^(\d{4}|\d{6}|\d{8})$/;

/** HSN rate in force on a document date (latest effectiveFrom ≤ date). */
export function rateOn<T extends { code: string; effectiveFrom: string; gstRate: number }>(rows: T[], code: string, date: string): number | null {
  const hit = rows.filter((r) => r.code === code && r.effectiveFrom <= date).sort((a, b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0];
  return hit ? hit.gstRate : null;
}

/** Warehouse can be deactivated only when it holds no stock. */
export function canDeactivateGodown(stockQty: number): boolean {
  return stockQty <= 0;
}
