// GENERATED by server/scripts/sync-shared.mjs from src/lib/item-detail-rules.ts. Do not edit here.
/** Item editor rules are shared by the React UI, demo API and Express backend.
 * Only master fields and per-godown thresholds are editable. Inventory and
 * batches must be changed through posted stock documents, never this form.
 */
import type { Item } from "./types.js";

export type ItemThreshold = Pick<Item["stock"][number], "godownId" | "reorderLevel" | "maxLevel">;
export type ItemEditPatch = Partial<Omit<Item, "id" | "batches" | "stock">> & { stock?: ItemThreshold[] };

export const GST_ITEM_RATES = [0, 5, 12, 18, 28] as const;
const HSN = /^(\d{4}|\d{6}|\d{8})$/;
const roundQty = (n: number) => Math.round(n * 1000) / 1000;

export function hasItemInventory(item: Item): boolean {
  return item.stock.some((s) => s.onHand !== 0 || s.held !== 0) || item.batches.length > 0;
}

/** Canonicalize editable text to avoid meaningless whitespace-only changes. */
export function normaliseItemDraft(item: Item): Item {
  return {
    ...item,
    name: item.name.trim(), sku: item.sku.trim(), brand: item.brand.trim(),
    category: item.category.trim(), hsn: item.hsn.trim(), baseUom: item.baseUom.trim().toUpperCase(),
    conversions: item.conversions.map((c) => ({ ...c, uom: c.uom.trim().toUpperCase() })),
  };
}

export function itemEditProblems(draft: Item, original: Item, knownGodowns: readonly string[] = []): string[] {
  const d = normaliseItemDraft(draft);
  const problems: string[] = [];
  if (!d.name || d.name.length > 200) problems.push("Item name is required (up to 200 characters).");
  if (!d.sku || d.sku.length > 40) problems.push("SKU is required (up to 40 characters).");
  if (d.brand.length > 80 || d.category.length > 80) problems.push("Brand and category must be at most 80 characters.");
  if (!HSN.test(d.hsn)) problems.push("HSN must contain 4, 6, or 8 digits.");
  if (!GST_ITEM_RATES.includes(d.gstRate as (typeof GST_ITEM_RATES)[number])) problems.push("Select a supported GST rate.");
  if (!Number.isFinite(d.salePrice) || d.salePrice < 0 || d.salePrice > 99999999999) problems.push("Sale price must be a valid non-negative amount.");
  if (!Number.isFinite(d.costPrice) || d.costPrice < 0 || d.costPrice > 99999999999) problems.push("Cost price must be a valid non-negative amount.");
  if (!d.baseUom || d.baseUom.length > 12) problems.push("Base unit is required (up to 12 characters).");

  if (!d.conversions.length) problems.push("At least the base-unit conversion is required.");
  const names = new Set<string>();
  for (const c of d.conversions) {
    if (!c.uom || c.uom.length > 12) problems.push("Every conversion needs a unit name (up to 12 characters).");
    if (names.has(c.uom)) problems.push(`Unit ${c.uom || "(empty)"} is listed more than once.`);
    names.add(c.uom);
    if (!Number.isFinite(c.factor) || c.factor <= 0 || c.factor > 1_000_000_000) problems.push(`Conversion factor for ${c.uom || "a unit"} must be positive.`);
  }
  if (!d.conversions.some((c) => c.uom === d.baseUom && c.factor === 1)) problems.push("Base unit must have conversion factor 1.");
  if (hasItemInventory(original)) {
    if (d.baseUom !== original.baseUom) problems.push("Base unit cannot change once stock or batches exist.");
    if (d.trackBatches !== original.trackBatches) problems.push("Batch tracking cannot change once stock or batches exist.");
    if (original.active && !d.active) problems.push("Move or release all on-hand and held stock before deactivating.");
  }

  const seen = new Set<string>();
  for (const s of d.stock) {
    if (!s.godownId || seen.has(s.godownId)) problems.push("Each godown must appear only once.");
    seen.add(s.godownId);
    if (knownGodowns.length && !knownGodowns.includes(s.godownId)) problems.push("An item setting points to a godown outside this organisation.");
    if (![s.reorderLevel, s.maxLevel].every((n) => Number.isFinite(n) && n >= 0 && n <= 999999999999)) problems.push("Reorder and maximum levels must be non-negative numbers.");
    if (s.maxLevel > 0 && roundQty(s.maxLevel) < roundQty(s.reorderLevel)) problems.push("Maximum stock cannot be below the reorder level.");
  }
  return [...new Set(problems)];
}

const EDIT_FIELDS = ["sku", "name", "category", "brand", "hsn", "gstRate", "baseUom", "conversions", "salePrice", "costPrice", "allowNegative", "trackBatches", "active"] as const;

/** Only send changed master fields and changed thresholds (never onHand, held or batches). */
export function itemEditPatch(original: Item, draft: Item): ItemEditPatch {
  const d = normaliseItemDraft(draft);
  const patch: ItemEditPatch = {};
  for (const field of EDIT_FIELDS) {
    if (JSON.stringify(d[field]) !== JSON.stringify(original[field])) {
      // The assignment is safe because every field belongs to ItemEditPatch.
      Object.assign(patch, { [field]: d[field] });
    }
  }
  const thresholds = d.stock.filter((s) => {
    const old = original.stock.find((x) => x.godownId === s.godownId);
    return !old || s.reorderLevel !== old.reorderLevel || s.maxLevel !== old.maxLevel;
  }).map(({ godownId, reorderLevel, maxLevel }) => ({ godownId, reorderLevel, maxLevel }));
  if (thresholds.length) patch.stock = thresholds;
  return patch;
}

/** India business date, independent of the browser/server operating-system timezone. */
export function indiaItemDate(instant: Date = new Date()): string {
  return new Date(instant.getTime() + 330 * 60_000).toISOString().slice(0, 10);
}

export function calendarDaysBetween(a: string, b: string): number {
  const day = (s: string) => Date.parse(`${s.slice(0, 10)}T00:00:00Z`);
  return Math.round((day(b) - day(a)) / 86_400_000);
}
