// GENERATED by scripts/sync-shared.mjs from frontend/src/lib/party-rules.ts. Do not edit here.
/** Customer, supplier and transporter master rules shared by React, demo and Express. */
import type { Party, PartyInput, PartyKind } from "./types.js";
import { isValidGstin, stateFromGstin } from "./gst.js";

export const PARTY_STATE_NAMES: Record<string, string> = {
  "01": "Jammu and Kashmir", "02": "Himachal Pradesh", "03": "Punjab", "04": "Chandigarh", "05": "Uttarakhand", "06": "Haryana",
  "07": "Delhi", "08": "Rajasthan", "09": "Uttar Pradesh", "10": "Bihar", "11": "Sikkim", "12": "Arunachal Pradesh", "13": "Nagaland",
  "14": "Manipur", "15": "Mizoram", "16": "Tripura", "17": "Meghalaya", "18": "Assam", "19": "West Bengal", "20": "Jharkhand",
  "21": "Odisha", "22": "Chhattisgarh", "23": "Madhya Pradesh", "24": "Gujarat", "26": "Dadra and Nagar Haveli and Daman and Diu",
  "27": "Maharashtra", "29": "Karnataka", "30": "Goa", "31": "Lakshadweep", "32": "Kerala", "33": "Tamil Nadu", "34": "Puducherry",
  "35": "Andaman and Nicobar Islands", "36": "Telangana", "37": "Andhra Pradesh", "38": "Ladakh", "97": "Other Territory",
};
export const partyStateName = (code: string): string => PARTY_STATE_NAMES[code] ?? `State ${code}`;
const KINDS: readonly string[] = ["customer", "supplier", "both", "transporter"];

export function normaliseParty(input: PartyInput): PartyInput {
  const gstin = (input.gstin ?? "").trim().toUpperCase();
  return {
    ...input,
    name: input.name.trim(), kind: input.kind,
    tradeName: input.tradeName?.trim() || undefined,
    gstin: gstin || undefined,
    pan: input.pan?.trim().toUpperCase() || (gstin && isValidGstin(gstin) ? gstin.slice(2, 12) : undefined),
    phone: input.phone.trim(), email: input.email?.trim().toLowerCase() || undefined,
    address: input.address?.trim() || undefined, city: input.city.trim(), pin: input.pin?.trim() || undefined,
    stateCode: input.stateCode.trim(),
  };
}

/** Never accept a client-provided outstanding balance: only posted financial documents change it. */
export function partyProblems(input: PartyInput): string[] {
  const d = normaliseParty(input);
  const issues: string[] = [];
  if (!KINDS.includes(d.kind)) issues.push("Choose a valid party type");
  if (!d.name || d.name.length > 200) issues.push("Party name is required (max 200 characters)");
  if ((d.tradeName?.length ?? 0) > 200) issues.push("Trade name cannot exceed 200 characters");
  if (!PARTY_STATE_NAMES[d.stateCode]) issues.push("Choose a valid two-digit GST state code");
  if ((d.city?.length ?? 0) > 120) issues.push("City cannot exceed 120 characters");
  if ((d.address?.length ?? 0) > 400) issues.push("Billing address cannot exceed 400 characters");
  if (d.pin && !/^\d{6}$/.test(d.pin)) issues.push("PIN must have exactly six digits");
  if (d.phone.length > 40 || (d.phone && !/^[+()\d\s-]+$/.test(d.phone))) issues.push("Enter a valid contact number (max 40 characters)");
  if (d.email && (d.email.length > 190 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))) issues.push("Enter a valid email address");
  if (d.pan && !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(d.pan)) issues.push("PAN must contain 10 valid characters");
  if (d.gstin) {
    if (!isValidGstin(d.gstin)) issues.push("GSTIN is invalid (format or checksum)");
    else {
      if (stateFromGstin(d.gstin) !== d.stateCode) issues.push("GSTIN state must match the party state code");
      if (d.pan && d.pan !== d.gstin.slice(2, 12)) issues.push("PAN must match the GSTIN");
    }
  }
  if (!Number.isFinite(d.creditLimit) || d.creditLimit < 0 || d.creditLimit > 9999999999999.99 ||
    Math.abs(Math.round(d.creditLimit * 100) - d.creditLimit * 100) > 1e-6) issues.push("Credit limit must be a non-negative amount with at most two decimals");
  if (!Number.isInteger(d.creditDays) || (d.creditDays ?? 0) < 0 || (d.creditDays ?? 0) > 3650) issues.push("Credit days must be a whole number between 0 and 3650");
  if (typeof d.blocked !== "boolean") issues.push("Blocked status must be true or false");
  return issues;
}

/** Apply organisation ownership before any search, detail read or duplicate check in demo mode. */
export function partiesForOrg(parties: readonly Party[], ownerById: Readonly<Record<string, string>>, orgId: string): Party[] {
  return orgId ? parties.filter((p) => ownerById[p.id] === orgId) : [];
}

export function duplicatePartyGstin(parties: readonly Party[], input: PartyInput): Party | undefined {
  const gstin = input.gstin?.trim().toUpperCase();
  return gstin ? parties.find((p) => p.id !== input.id && p.gstin?.toUpperCase() === gstin) : undefined;
}

export type PartyTypeFilter = "all" | PartyKind;
export type PartyStatusFilter = "all" | "blocked" | "unblocked";
export function filterParties(parties: readonly Party[], type: PartyTypeFilter, query: string, status: PartyStatusFilter): Party[] {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return parties.filter((p) => {
    if (type !== "all" && p.kind !== type && !(p.kind === "both" && (type === "customer" || type === "supplier"))) return false;
    if (status === "blocked" && !p.blocked) return false;
    if (status === "unblocked" && p.blocked) return false;
    const haystack = [p.name, p.tradeName, p.gstin, p.pan, p.city, p.stateName, p.phone, p.email].join(" ").toLocaleLowerCase();
    return terms.every((term) => haystack.includes(term));
  }).sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
}

export function partyCreditSummary(p: Party): { headroom: number; nearLimit: boolean } {
  const headroom = Math.round((p.creditLimit - p.outstanding) * 100) / 100;
  return { headroom, nearLimit: p.creditLimit > 0 && headroom < p.creditLimit * 0.25 };
}
