// GENERATED by scripts/sync-shared.mjs from frontend/src/lib/permissions.ts. Do not edit here.
import type { Role } from "./types.js";

/** Single source of truth for what each role may do (spec 0.1). The UI hides buttons; the server enforces the same table. */
export const PERMISSIONS = {
  editItems: ["Owner", "Manager"],
  editMasters: ["Owner", "Manager"],
  editParties: ["Owner", "Manager", "Sales"],
  salesOrders: ["Owner", "Manager", "Sales"],
  overrideCredit: ["Owner"],
  dispatch: ["Owner", "Manager", "Storekeeper"],
  issueInvoice: ["Owner", "Manager", "Accountant"],
  recordReceipt: ["Owner", "Manager", "Accountant"],
  raisePO: ["Owner", "Manager"],
  postGrn: ["Owner", "Manager", "Storekeeper"],
  transfer: ["Owner", "Manager", "Storekeeper"],
  cancelTransfer: ["Owner", "Manager"],
  adjust: ["Owner", "Manager", "Storekeeper"],
  approveAdjustment: ["Owner", "Manager"],
  reports: ["Owner", "Manager", "Accountant"],
  printProfiles: ["Owner", "Manager"],
  manageUsers: ["Owner"],
  settings: ["Owner"],
} as const satisfies Record<string, readonly Role[]>;

export type Permission = keyof typeof PERMISSIONS;

export const PERMISSION_LABELS: Record<Permission, string> = {
  editItems: "Edit items",
  editMasters: "Edit units, categories, HSN, godowns",
  editParties: "Add and edit parties",
  salesOrders: "Create and confirm sales orders",
  overrideCredit: "Override credit limit",
  dispatch: "Dispatch challans and e-way bills",
  issueInvoice: "Issue tax invoices",
  recordReceipt: "Record receipts",
  raisePO: "Raise purchase orders",
  postGrn: "Receive goods (GRN)",
  transfer: "Send and receive transfers",
  cancelTransfer: "Cancel transfers",
  adjust: "Create stock adjustments",
  approveAdjustment: "Approve adjustments",
  reports: "Reports and GSTR-1",
  printProfiles: "Print profiles",
  manageUsers: "Manage users",
  settings: "Organisation settings and numbering",
};

export function can(role: Role | string | undefined, p: Permission): boolean {
  return !!role && (PERMISSIONS[p] as readonly string[]).includes(role);
}
