// GENERATED by scripts/sync-shared.mjs from frontend/src/lib/receipt-rules.ts. Do not edit here.
/** Stage 11 receipt posting rules; shared by React, mock and Express. */
export type ReceiptMode = 'cash' | 'upi' | 'neft' | 'cheque';
export interface ReceiptOpenInvoice { id: string; date: string; balance: number; number?: string }
export interface ReceiptDraft {
  customerId: string; date: string; amount: number; mode: string; reference: string;
  allocations?: { invoiceId: string; amount: number }[] | null;
}

/** Convert exact, two-decimal currency to integer paise (or reject it). */
export function receiptPaise(value: number): number | null {
  if (!Number.isFinite(value) || value < 0 || value > 999_999_999_999.99) return null;
  const scaled = value * 100;
  return Math.abs(scaled - Math.round(scaled)) <= 0.00001 ? Math.round(scaled) : null;
}
const validDate = (date: string) => /^\d{4}-\d{2}-\d{2}$/.test(date) &&
  Number.isFinite(Date.parse(`${date}T00:00:00Z`)) && new Date(`${date}T00:00:00Z`).toISOString().slice(0, 10) === date;

/** Check the complete instruction before generating a receipt number or changing a balance. */
export function receiptProblems(input: ReceiptDraft, open: ReceiptOpenInvoice[], businessToday: string): string[] {
  const errors: string[] = [];
  if (!input.customerId.trim()) errors.push('Choose a customer');
  if (!validDate(input.date)) errors.push('Enter a valid receipt date');
  else if (input.date > businessToday) errors.push('Receipt date cannot be in the future');
  const amount = receiptPaise(input.amount);
  if (amount === null || amount <= 0) errors.push('Enter a positive amount with at most two decimal places');
  if (!['cash', 'upi', 'neft', 'cheque'].includes(input.mode)) errors.push('Choose a valid payment mode');
  if (input.mode !== 'cash' && !input.reference.trim()) errors.push('Add the UTR, UPI or cheque reference');
  if (input.reference.length > 200) errors.push('Reference is too long (maximum 200 characters)');
  if (input.allocations !== undefined && input.allocations !== null) {
    if (input.allocations.length > 500) errors.push('Too many invoice allocations');
    const ids = new Set<string>();
    let allocated = 0;
    for (const a of input.allocations) {
      if (ids.has(a.invoiceId)) errors.push('Cannot allocate the same invoice twice');
      ids.add(a.invoiceId);
      const invoice = open.find((i) => i.id === a.invoiceId);
      if (!invoice) errors.push('Invoice is not open for this customer');
      const paise = receiptPaise(a.amount);
      if (paise === null || paise < 0) errors.push('Allocations must be non-negative amounts with at most two decimals');
      else allocated += paise;
      if (invoice && paise !== null && paise > (receiptPaise(invoice.balance) ?? -1)) errors.push(`More than the balance on ${invoice.number ?? invoice.id}`);
      if (invoice && paise !== null && paise > 0 && validDate(input.date) && input.date < invoice.date) errors.push(`Receipt date cannot precede ${invoice.number ?? invoice.id}`);
    }
    if (amount !== null && allocated > amount) errors.push('Allocated more than the amount received');
  }
  return errors;
}

/** Always use paise during allocation, so 0.1 + 0.2 cannot create phantom advances. */
export function receiptAllocation(open: ReceiptOpenInvoice[], amount: number) {
  let left = receiptPaise(amount) ?? 0;
  const allocations: { invoiceId: string; amount: number }[] = [];
  for (const i of [...open].sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id))) {
    const paise = Math.min(left, receiptPaise(i.balance) ?? 0);
    if (paise > 0) { allocations.push({ invoiceId: i.id, amount: paise / 100 }); left -= paise; }
    if (!left) break;
  }
  return { allocations, advance: left / 100 };
}

export function receiptsForOrg<T extends { id: string }>(rows: T[], owners: Record<string, string>, orgId: string): T[] {
  return rows.filter((row) => !!orgId && owners[row.id] === orgId);
}
export function filterReceipts<T extends { number: string; date: string; customerName: string; mode: string; reference: string; allocations: { invoiceNo: string }[] }>(rows: T[], search: string): T[] {
  const tokens = search.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return rows.filter((r) => tokens.every((t) => `${r.number} ${r.date} ${r.customerName} ${r.mode} ${r.reference} ${r.allocations.map((a) => a.invoiceNo).join(' ')}`.toLocaleLowerCase().includes(t)))
    .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
}
