// GENERATED by server/scripts/sync-shared.mjs from src/lib/search-rules.ts. Do not edit here.
import type { DocHit, SearchFilter } from "./types.js";

export function periodStart(period: SearchFilter["period"], today: string): string | null {
  const d = new Date(today + "T00:00:00Z");
  if (period === "today") return today;
  if (period === "7d") d.setUTCDate(d.getUTCDate() - 6);
  else if (period === "30d") d.setUTCDate(d.getUTCDate() - 29);
  else if (period === "fy") return `${d.getUTCMonth() >= 3 ? d.getUTCFullYear() : d.getUTCFullYear() - 1}-04-01`;
  else return null;
  return d.toISOString().slice(0, 10);
}

/** Case-insensitive match on number or party; filters by type, status, period and amount range; newest first. */
export function filterDocs(docs: DocHit[], f: SearchFilter, today: string): DocHit[] {
  const q = (f.q ?? "").trim().toLowerCase();
  const from = periodStart(f.period, today);
  return docs
    .filter((d) => !q || d.number.toLowerCase().includes(q) || d.party.toLowerCase().includes(q))
    .filter((d) => !f.types?.length || f.types.includes(d.type))
    .filter((d) => !f.status || d.status === f.status)
    .filter((d) => !from || d.date >= from)
    .filter((d) => f.min == null || d.amount >= f.min)
    .filter((d) => f.max == null || d.amount <= f.max)
    .sort((a, b) => b.date.localeCompare(a.date) || b.number.localeCompare(a.number));
}
