// GENERATED by scripts/sync-shared.mjs from frontend/src/api/types.ts. Do not edit here.
export type Role = "Owner" | "Manager" | "Storekeeper" | "Sales" | "Accountant" | "Driver";
export const ROLES: Role[] = ["Owner", "Manager", "Storekeeper", "Sales", "Accountant", "Driver"];

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
}

export interface Org {
  id: string;
  name: string;
  gstin: string;
  stateCode: string;
  stateName: string;
}

export interface WarehouseDayFlow { date: string; incomingValue: number; outgoingValue: number }
export interface WarehouseActivity {
  godownId: string;
  fromDate: string;
  toDate: string;
  incomingValue: number;
  outgoingValue: number;
  incomingMovements: number;
  outgoingMovements: number;
  daily: WarehouseDayFlow[];
  recent: LedgerEntry[];
}

export interface Godown {
  id: string;
  orgId: string;
  name: string;
  code: string;
  type?: GodownType;
  address?: string;
  stateCode?: string;
  gstin?: string | undefined;
  manager?: string;
  allowNegative?: boolean;
  defaultForSales?: boolean;
  active?: boolean;
  stockValue?: number;
  stockQty?: number;
  heldQty?: number;
  itemCount?: number;
}

export interface LoginResponse {
  token: string;
  user: User;
  orgs: Org[];
}

export interface UomConversion {
  uom: string;
  factor: number; // base units per this uom
}

export interface Batch {
  id: string;
  batchNo: string;
  godownId: string;
  qty: number;
  mfgDate: string;
  expiryDate?: string;
  receivedDate: string;
  heatNo?: string;
}

export interface ItemGodownStock {
  godownId: string;
  onHand: number;
  held: number;
  reorderLevel: number;
  maxLevel: number;
}

export interface Item {
  id: string;
  sku: string;
  name: string;
  category: string;
  brand: string;
  hsn: string;
  gstRate: number;
  baseUom: string;
  conversions: UomConversion[];
  salePrice: number;
  costPrice: number;
  allowNegative: boolean;
  trackBatches: boolean;
  stock: ItemGodownStock[];
  batches: Batch[];
  active: boolean;
}

export type PartyKind = "customer" | "supplier" | "both" | "transporter";

export interface Party {
  id: string;
  kind: PartyKind;
  name: string;
  tradeName?: string;
  pan?: string;
  email?: string;
  address?: string;
  pin?: string;
  creditDays?: number;
  blocked?: boolean;
  gstin?: string | undefined;
  stateCode: string;
  stateName: string;
  city: string;
  phone: string;
  creditLimit: number;
  outstanding: number;
}

export type SOStatus = "draft" | "confirmed" | "partially_delivered" | "delivered" | "cancelled";

export interface SOLine {
  id: string;
  itemId: string;
  itemName: string;
  hsn: string;
  uom: string;
  qty: number;
  deliveredQty: number;
  rate: number;
  discountPct: number;
  gstRate: number;
}

export interface LinkedDoc {
  type: "delivery_challan" | "tax_invoice" | "receipt" | "sales_order";
  number: string;
  date: string;
  status: string;
  amount: number;
}

export interface SalesOrder {
  id: string;
  number: string | null;
  date: string;
  customerId: string;
  customerName: string;
  placeOfSupplyCode: string;
  placeOfSupplyName: string;
  godownId: string;
  status: SOStatus;
  lines: SOLine[];
  notes: string;
  grandTotal: number;
  creditOverride?: { by: string; reason: string; at: string };
  linked: LinkedDoc[];
}

export interface SalesOrderInput {
  id?: string | undefined;
  date: string;
  customerId: string;
  godownId: string;
  lines: Omit<SOLine, "id" | "deliveredQty">[];
  notes: string;
}

export interface Movement {
  id: string;
  date: string;
  docNo: string;
  type: "Sale" | "Purchase" | "Transfer" | "Adjustment";
  itemName: string;
  godownName: string;
  qty: number;
  value: number;
}

export interface AttentionItem {
  id: string;
  kind: "out_of_stock" | "low_stock" | "near_expiry" | "over_aged" | "overdue" | "ewb_expiring";
  title: string;
  detail: string;
}

export interface Dashboard {
  /** Business date of the snapshot, YYYY-MM-DD (Asia/Kolkata on the real API). */
  asOfDate: string;
  stockValue: number;
  movementsToday: number;
  nearExpiry: number;
  overAged: number;
  lowStock: number;
  outOfStock: number;
  valueByGodown: { godownId: string; name: string; value: number }[];
  highValueMovements: Movement[];
  attention: AttentionItem[];
  pipeline: { stage: string; count: number; value: number }[];
}

export interface Notification {
  id: string;
  title: string;
  time: string;
  read: boolean;
}

// ---------- Masters ----------
export interface Uom {
  id: string;
  code: string;
  name: string;
  category: "weight" | "count" | "length" | "volume" | "area";
  decimals: number;
  active: boolean;
}

export interface Category {
  id: string;
  name: string;
  parentId: string | null;
  defaultHsn: string;
  defaultGst: number;
  active: boolean;
}

export interface Brand {
  id: string;
  name: string;
  active: boolean;
}

export interface HsnRate {
  id: string;
  code: string;
  description: string;
  gstRate: number;
  cessPct: number;
  effectiveFrom: string;
  active: boolean;
}

export interface MasterRows {
  uoms: Uom;
  categories: Category;
  brands: Brand;
  hsn: HsnRate;
}
export type MasterKind = keyof MasterRows;

export type GodownType = "godown" | "yard" | "shop_counter" | "transit";
export interface GodownInput {
  id?: string | undefined;
  code: string;
  name: string;
  type: GodownType;
  address: string;
  stateCode: string;
  gstin?: string | undefined;
  manager: string;
  allowNegative: boolean;
  defaultForSales: boolean;
  active: boolean;
}

export type PartyInput = Omit<Party, "id" | "outstanding" | "stateName"> & { id?: string | undefined };

// ---------- Stock ledger & alerts ----------
export type LedgerType =
  | "OPENING" | "PURCHASE_IN" | "TRANSFER_IN" | "TRANSFER_OUT" | "DC_ISSUE" | "DC_REVERSE" | "ADJ_IN" | "ADJ_OUT";

export interface LedgerEntry {
  id: string;
  at: string; // ISO datetime
  docNo: string;
  docType: "opening" | "grn" | "transfer" | "challan" | "adjustment";
  soId?: string;
  type: LedgerType;
  itemId: string;
  itemName: string;
  godownId: string;
  godownName: string;
  batchNo?: string;
  qty: number; // signed, base UOM
  unitCost: number;
  user: string;
  reason?: string;
}

export interface LedgerFilter {
  itemId?: string | undefined;
  godownId?: string | undefined;
  batchNo?: string | undefined;
  type?: LedgerType | undefined;
  from?: string | undefined;
  to?: string | undefined;
  docNo?: string | undefined;
}

export type AlertKind = "out_of_stock" | "below_reorder" | "near_expiry" | "over_aged";

export interface StockAlert {
  id: string;
  kind: AlertKind;
  itemId: string;
  itemName: string;
  sku: string;
  uom: string;
  godownId: string;
  godownName: string;
  qty: number;
  batchNo?: string;
  reorderLevel?: number;
  shortfall?: number;
  expiryDate?: string;
  daysLeft?: number;
  ageDays?: number;
  valueAtRisk: number;
  acknowledged: boolean;
}

// ---------- Delivery challans ----------
export type ChallanStatus = "in_transit" | "delivered" | "cancelled";

export interface ChallanAllocation {
  batchNo?: string | undefined;
  qty: number;
}

export interface ChallanLine {
  soLineId: string;
  itemId: string;
  itemName: string;
  hsn: string;
  uom: string;
  qty: number;
  rate: number;
  discountPct: number;
  gstRate: number;
  allocations: ChallanAllocation[];
}

export interface EwayBill {
  number: string;
  generatedAt: string;
  validUntil: string;
  vehicleNo: string;
  distanceKm: number;
  status: "active" | "cancelled";
  history: { at: string; action: string; by: string }[];
}

export interface ChallanEvent {
  at: string;
  label: string;
  by: string;
  note?: string | undefined;
}

export interface Challan {
  id: string;
  number: string;
  date: string;
  soId: string;
  soNumber: string;
  customerId: string;
  customerName: string;
  placeOfSupplyCode: string;
  placeOfSupplyName: string;
  godownId: string;
  godownName: string;
  status: ChallanStatus;
  lines: ChallanLine[];
  taxable: number;
  tax: number;
  value: number;
  vehicleNo: string;
  driverName: string;
  driverPhone: string;
  transporter: string;
  distanceKm: number;
  overrideReason?: string | undefined;
  ewb?: EwayBill | undefined;
  pod?: { at: string; receivedBy: string; remarks: string; by: string } | undefined;
  events: ChallanEvent[];
  invoiceNo?: string | undefined;
}

export interface DispatchInput {
  soId: string;
  lines: { soLineId: string; qty: number; allocations: ChallanAllocation[] }[];
  vehicleNo: string;
  driverName: string;
  driverPhone: string;
  transporter: string;
  distanceKm: number;
  overrideReason?: string | undefined;
}

export type EwbAction =
  | { action: "extend"; extraKm: number; reason: string }
  | { action: "part-b"; vehicleNo: string; reason: string }
  | { action: "cancel"; reason: string };

// ---------- Tax invoices ----------
export interface Advance {
  id: string;
  receiptNo: string;
  date: string;
  customerId: string;
  amount: number;
  remaining: number;
}

export interface Invoice {
  id: string;
  number: string;
  date: string;
  dueDate: string;
  customerId: string;
  customerName: string;
  gstin?: string | undefined;
  placeOfSupplyCode: string;
  placeOfSupplyName: string;
  supply: "intra" | "inter";
  challans: { id: string; number: string; soId: string; soNumber: string }[];
  lines: ChallanLine[];
  taxable: number;
  cgst: number;
  sgst: number;
  igst: number;
  roundOff: number;
  grandTotal: number;
  byRate: { rate: number; taxable: number; tax: number }[];
  advances: { advanceId: string; receiptNo: string; amount: number }[];
  paid: number;
  balance: number;
  status: "awaiting_payment" | "partially_paid" | "paid" | "overdue" | "cancelled";
  createdBy: string;
  cancelled?: { at: string; by: string; reason: string };
}

export interface IssueInvoiceInput {
  challanIds: string[];
  date: string;
  applyAdvances: boolean;
}

export type PaymentMode = "cash" | "upi" | "neft" | "cheque";
export interface Receipt {
  id: string;
  number: string;
  date: string;
  customerId: string;
  customerName: string;
  amount: number;
  mode: PaymentMode;
  reference: string;
  allocations: { invoiceId: string; invoiceNo: string; amount: number }[];
  advance: number;
  createdBy: string;
}
export interface ReceiptInput {
  customerId: string;
  date: string;
  amount: number;
  mode: PaymentMode;
  reference: string;
  /** Explicit split; omitted = oldest invoice first. */
  allocations?: { invoiceId: string; amount: number }[] | undefined;
}

// ---------- Purchases / GRN ----------
export interface PoLine { id: string; itemId: string; itemName: string; hsn: string; uom: string; gstRate: number; qty: number; receivedQty: number; rate: number }
export interface PurchaseOrder {
  id: string; number: string; date: string; supplierId: string; supplierName: string; godownId: string; godownName: string;
  status: "draft" | "open" | "partially_received" | "received" | "cancelled"; lines: PoLine[]; grandTotal: number; notes: string;
  grns: { id: string; number: string; date: string }[]; createdBy: string;
  approvedBy?: string | undefined; cancelledBy?: string | undefined; cancellationReason?: string | undefined;
}
export interface PurchaseOrderInput {
  date: string; supplierId: string; godownId: string; notes: string;
  draft?: boolean | undefined;
  lines: { itemId: string; qty: number; rate: number }[];
}
export interface GrnLine {
  poLineId?: string | undefined; itemId: string; itemName: string; hsn: string; uom: string; gstRate: number;
  ordered?: number | undefined; received: number; accepted: number; rejected: number; rate: number;
  batchNo?: string | undefined; mfgDate?: string | undefined; expiryDate?: string | undefined; rejectionReason?: string | undefined;
  freightShare: number; landedCost: number;
}
export interface Grn {
  id: string; number: string; date: string; supplierId: string; supplierName: string; poId?: string | undefined; poNumber?: string | undefined;
  supplierInvoiceNo: string; supplierInvoiceDate: string; godownId: string; godownName: string; vehicleNo: string;
  freight: number; lines: GrnLine[]; taxable: number; tax: number; grandTotal: number; createdBy: string;
}
export interface GrnInput {
  date: string; supplierId: string; poId?: string | undefined; supplierInvoiceNo: string; supplierInvoiceDate: string;
  godownId: string; vehicleNo: string; freight: number;
  lines: { poLineId?: string | undefined; itemId: string; received: number; rejected: number; rate: number; batchNo?: string | undefined; mfgDate?: string | undefined; expiryDate?: string | undefined; rejectionReason?: string | undefined }[];
}

// ---------- Transfers ----------
export interface TransferLine { itemId: string; itemName: string; uom: string; batchNo?: string | undefined; qty: number; receivedQty?: number | undefined; shortReason?: string | undefined; unitCost: number }
export interface Transfer {
  id: string; number: string; date: string; fromId: string; fromName: string; toId: string; toName: string;
  status: "in_transit" | "received" | "partially_received" | "cancelled"; vehicleNo: string; reason: string;
  lines: TransferLine[]; value: number; events: { at: string; label: string; by: string; note?: string | undefined }[];
}
export interface TransferInput { date: string; fromId: string; toId: string; vehicleNo: string; reason: string; lines: { itemId: string; batchNo?: string | undefined; qty: number }[] }
export interface ReceiveTransferInput { lines: { received: number; reason?: string | undefined }[] }

export interface AdjustmentLine { itemId: string; itemName: string; uom: string; batchNo?: string | undefined; direction: "up" | "down"; qty: number; unitCost: number }
export interface Adjustment {
  id: string; number: string; date: string; godownId: string; godownName: string; reason: string; notes: string;
  status: "pending_approval" | "posted" | "rejected"; lines: AdjustmentLine[]; valueUp: number; valueDown: number;
  createdBy: string; createdByRole: string; events: { at: string; label: string; by: string; note?: string | undefined }[];
}
export interface AdjustmentInput { date: string; godownId: string; reason: string; notes: string; lines: { itemId: string; batchNo?: string | undefined; direction: "up" | "down"; qty: number; unitCost: number }[] }

// ---------- Users ----------
export interface AppUser { id: string; name: string; email: string; mobile: string; role: Role; godownIds: string[]; active: boolean; lastLogin?: string | undefined; invitePending?: boolean | undefined }
export interface AppUserInput { id?: string | undefined; name: string; email: string; mobile: string; role: Role; godownIds: string[]; active: boolean }

// ---------- Numbering ----------
export type DocType = "SO" | "DC" | "INV" | "RCT" | "PO" | "GRN" | "TRF" | "ADJ";
export interface NumberSeries { docType: DocType; label: string; prefix: string; fy: string; lastNumber: number; padding: number; resetPerFy: boolean; locked: boolean }
export interface NumberSeriesInput { docType: DocType; prefix: string; padding: number; resetPerFy: boolean }

// ---------- Settings ----------
export interface ReasonCode { id: string; type: "adjustment" | "return" | "override" | "cancellation"; code: string; label: string; active: boolean }
export interface OrgSettings {
  legalName: string; tradeName: string; gstin: string; pan: string; address: string; stateCode: string; phone: string; email: string;
  bankName: string; bankAccount: string; ifsc: string; invoiceTerms: string; jurisdiction: string;
  fyName: string; fyStart: string; fyEnd: string; fyStatus: "open" | "closed";
  composition: boolean; ewbThreshold: number; einvoiceThreshold: number; roundOff: "nearest_rupee" | "none"; adjApprovalLimit: number;
  reasonCodes: ReasonCode[];
  gsp: { provider: string; username: string; clientId: string; sandbox: boolean; secretSet: boolean };
}
export type OrgSettingsInput = Omit<OrgSettings, "gsp"> & { gsp: { provider: string; username: string; clientId: string; sandbox: boolean; secret?: string | undefined } };

// ---------- Print profiles ----------
export interface PrintProfile { id: "A" | "B"; name: string; paper: "80mm" | "A4"; showLogo: boolean; showBank: boolean; showHsnSummary: boolean; showSignature: boolean; showQr: boolean; copies: number; footer: string }

// ---------- Search ----------
export type SearchDocType = "SO" | "DC" | "INV" | "RCT";
export interface DocHit { type: SearchDocType; id: string; number: string; date: string; party: string; amount: number; status: string }
export interface SearchFilter { q?: string | undefined; types?: SearchDocType[] | undefined; status?: string | undefined; period?: "today" | "7d" | "30d" | "fy" | "all" | undefined; min?: number | undefined; max?: number | undefined }

// ---------- Reports ----------
export interface SalesRegisterRow { id: string; number: string; date: string; customer: string; gstin?: string | undefined; taxable: number; cgst: number; sgst: number; igst: number; total: number; status: string }
export interface ReceivableRow { customerId: string; customer: string; invoices: number; current: number; d30: number; d60: number; d90: number; over90: number; total: number }
export interface ItemSalesRow { itemId: string; item: string; hsn: string; uom: string; qty: number; taxable: number; cost: number; margin: number }
export interface Gstr1 {
  period: string; gstin: string;
  b2b: { gstin: string; name: string; invoiceNo: string; date: string; value: number; pos: string; rate: number; taxable: number; igst: number; cgst: number; sgst: number }[];
  b2cl: { invoiceNo: string; date: string; value: number; pos: string; rate: number; taxable: number; igst: number }[];
  b2cs: { pos: string; supply: "intra" | "inter"; rate: number; taxable: number; igst: number; cgst: number; sgst: number }[];
  hsn: { recipient: "b2b" | "b2c"; hsn: string; uom: string; qty: number; rate: number; taxable: number; igst: number; cgst: number; sgst: number }[];
  docs: { nature: string; from: string; to: string; total: number; cancelled: number }[];
  totals: { taxable: number; igst: number; cgst: number; sgst: number; invoices: number };
}
