/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedNoAccessRouteImport } from './routes/_authenticated/no-access'
import { Route as AuthenticatedNumberingRouteImport } from './routes/_authenticated/numbering'
import { Route as AuthenticatedPartiesRouteImport } from './routes/_authenticated/parties'
import { Route as AuthenticatedPrintProfilesRouteImport } from './routes/_authenticated/print-profiles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStockLedgerRouteImport } from './routes/_authenticated/stock-ledger'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedAdjustmentsIndexRouteImport } from './routes/_authenticated/adjustments.index'
import { Route as AuthenticatedAdjustmentsIdRouteImport } from './routes/_authenticated/adjustments.$id'
import { Route as AuthenticatedAdjustmentsNewRouteImport } from './routes/_authenticated/adjustments.new'
import { Route as AuthenticatedChallansIndexRouteImport } from './routes/_authenticated/challans.index'
import { Route as AuthenticatedChallansIdRouteImport } from './routes/_authenticated/challans.$id'
import { Route as AuthenticatedChallansNewRouteImport } from './routes/_authenticated/challans.new'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items.index'
import { Route as AuthenticatedItemsIdRouteImport } from './routes/_authenticated/items.$id'
import { Route as AuthenticatedPartiesIndexRouteImport } from './routes/_authenticated/parties.index'
import { Route as AuthenticatedPartiesIdRouteImport } from './routes/_authenticated/parties.$id'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedPurchasesIdRouteImport } from './routes/_authenticated/purchases.$id'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated/receipts.index'
import { Route as AuthenticatedReceiptsNewRouteImport } from './routes/_authenticated/receipts.new'
import { Route as AuthenticatedSalesOrdersIndexRouteImport } from './routes/_authenticated/sales-orders.index'
import { Route as AuthenticatedSalesOrdersIdRouteImport } from './routes/_authenticated/sales-orders.$id'
import { Route as AuthenticatedTransfersIndexRouteImport } from './routes/_authenticated/transfers.index'
import { Route as AuthenticatedTransfersIdRouteImport } from './routes/_authenticated/transfers.$id'
import { Route as AuthenticatedTransfersNewRouteImport } from './routes/_authenticated/transfers.new'
import { Route as AuthenticatedPurchasesGrnIdRouteImport } from './routes/_authenticated/purchases.grn.$id'
import { Route as AuthenticatedPurchasesGrnNewRouteImport } from './routes/_authenticated/purchases.grn.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoAccessRoute = AuthenticatedNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNumberingRoute = AuthenticatedNumberingRouteImport.update({
  id: '/numbering',
  path: '/numbering',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartiesRoute = AuthenticatedPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrintProfilesRoute =
  AuthenticatedPrintProfilesRouteImport.update({
    id: '/print-profiles',
    path: '/print-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockLedgerRoute =
  AuthenticatedStockLedgerRouteImport.update({
    id: '/stock-ledger',
    path: '/stock-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdjustmentsIndexRoute =
  AuthenticatedAdjustmentsIndexRouteImport.update({
    id: '/adjustments/',
    path: '/adjustments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdjustmentsIdRoute =
  AuthenticatedAdjustmentsIdRouteImport.update({
    id: '/adjustments/$id',
    path: '/adjustments/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdjustmentsNewRoute =
  AuthenticatedAdjustmentsNewRouteImport.update({
    id: '/adjustments/new',
    path: '/adjustments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChallansIndexRoute =
  AuthenticatedChallansIndexRouteImport.update({
    id: '/challans/',
    path: '/challans/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChallansIdRoute = AuthenticatedChallansIdRouteImport.update({
  id: '/challans/$id',
  path: '/challans/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallansNewRoute =
  AuthenticatedChallansNewRouteImport.update({
    id: '/challans/new',
    path: '/challans/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsIdRoute = AuthenticatedItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartiesIndexRoute =
  AuthenticatedPartiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartiesRoute,
  } as any)
const AuthenticatedPartiesIdRoute = AuthenticatedPartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPartiesRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesIdRoute =
  AuthenticatedPurchasesIdRouteImport.update({
    id: '/purchases/$id',
    path: '/purchases/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/purchases/new',
    path: '/purchases/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsNewRoute =
  AuthenticatedReceiptsNewRouteImport.update({
    id: '/receipts/new',
    path: '/receipts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesOrdersIndexRoute =
  AuthenticatedSalesOrdersIndexRouteImport.update({
    id: '/sales-orders/',
    path: '/sales-orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesOrdersIdRoute =
  AuthenticatedSalesOrdersIdRouteImport.update({
    id: '/sales-orders/$id',
    path: '/sales-orders/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransfersIndexRoute =
  AuthenticatedTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransfersIdRoute =
  AuthenticatedTransfersIdRouteImport.update({
    id: '/transfers/$id',
    path: '/transfers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransfersNewRoute =
  AuthenticatedTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesGrnIdRoute =
  AuthenticatedPurchasesGrnIdRouteImport.update({
    id: '/purchases/grn/$id',
    path: '/purchases/grn/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesGrnNewRoute =
  AuthenticatedPurchasesGrnNewRouteImport.update({
    id: '/purchases/grn/new',
    path: '/purchases/grn/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/numbering': typeof AuthenticatedNumberingRoute
  '/parties': typeof AuthenticatedPartiesRouteWithChildren
  '/print-profiles': typeof AuthenticatedPrintProfilesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-ledger': typeof AuthenticatedStockLedgerRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/adjustments/$id': typeof AuthenticatedAdjustmentsIdRoute
  '/adjustments/new': typeof AuthenticatedAdjustmentsNewRoute
  '/challans/$id': typeof AuthenticatedChallansIdRoute
  '/challans/new': typeof AuthenticatedChallansNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/parties/$id': typeof AuthenticatedPartiesIdRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/adjustments/': typeof AuthenticatedAdjustmentsIndexRoute
  '/challans/': typeof AuthenticatedChallansIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/items/': typeof AuthenticatedItemsIndexRoute
  '/parties/': typeof AuthenticatedPartiesIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/purchases/grn/$id': typeof AuthenticatedPurchasesGrnIdRoute
  '/purchases/grn/new': typeof AuthenticatedPurchasesGrnNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/numbering': typeof AuthenticatedNumberingRoute
  '/print-profiles': typeof AuthenticatedPrintProfilesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-ledger': typeof AuthenticatedStockLedgerRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/adjustments/$id': typeof AuthenticatedAdjustmentsIdRoute
  '/adjustments/new': typeof AuthenticatedAdjustmentsNewRoute
  '/challans/$id': typeof AuthenticatedChallansIdRoute
  '/challans/new': typeof AuthenticatedChallansNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/parties/$id': typeof AuthenticatedPartiesIdRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/adjustments': typeof AuthenticatedAdjustmentsIndexRoute
  '/challans': typeof AuthenticatedChallansIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/parties': typeof AuthenticatedPartiesIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
  '/purchases/grn/$id': typeof AuthenticatedPurchasesGrnIdRoute
  '/purchases/grn/new': typeof AuthenticatedPurchasesGrnNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/no-access': typeof AuthenticatedNoAccessRoute
  '/_authenticated/numbering': typeof AuthenticatedNumberingRoute
  '/_authenticated/parties': typeof AuthenticatedPartiesRouteWithChildren
  '/_authenticated/print-profiles': typeof AuthenticatedPrintProfilesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock-ledger': typeof AuthenticatedStockLedgerRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/adjustments/$id': typeof AuthenticatedAdjustmentsIdRoute
  '/_authenticated/adjustments/new': typeof AuthenticatedAdjustmentsNewRoute
  '/_authenticated/challans/$id': typeof AuthenticatedChallansIdRoute
  '/_authenticated/challans/new': typeof AuthenticatedChallansNewRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/items/$id': typeof AuthenticatedItemsIdRoute
  '/_authenticated/parties/$id': typeof AuthenticatedPartiesIdRoute
  '/_authenticated/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/_authenticated/sales-orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/_authenticated/transfers/$id': typeof AuthenticatedTransfersIdRoute
  '/_authenticated/transfers/new': typeof AuthenticatedTransfersNewRoute
  '/_authenticated/adjustments/': typeof AuthenticatedAdjustmentsIndexRoute
  '/_authenticated/challans/': typeof AuthenticatedChallansIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/parties/': typeof AuthenticatedPartiesIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/_authenticated/sales-orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/_authenticated/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/_authenticated/purchases/grn/$id': typeof AuthenticatedPurchasesGrnIdRoute
  '/_authenticated/purchases/grn/new': typeof AuthenticatedPurchasesGrnNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/import'
    | '/masters'
    | '/no-access'
    | '/numbering'
    | '/parties'
    | '/print-profiles'
    | '/reports'
    | '/search'
    | '/settings'
    | '/stock-ledger'
    | '/users'
    | '/warehouses'
    | '/adjustments/$id'
    | '/adjustments/new'
    | '/challans/$id'
    | '/challans/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/items/$id'
    | '/parties/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/receipts/new'
    | '/sales-orders/$id'
    | '/transfers/$id'
    | '/transfers/new'
    | '/adjustments/'
    | '/challans/'
    | '/invoices/'
    | '/items/'
    | '/parties/'
    | '/purchases/'
    | '/receipts/'
    | '/sales-orders/'
    | '/transfers/'
    | '/purchases/grn/$id'
    | '/purchases/grn/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/import'
    | '/masters'
    | '/no-access'
    | '/numbering'
    | '/print-profiles'
    | '/reports'
    | '/search'
    | '/settings'
    | '/stock-ledger'
    | '/users'
    | '/warehouses'
    | '/adjustments/$id'
    | '/adjustments/new'
    | '/challans/$id'
    | '/challans/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/items/$id'
    | '/parties/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/receipts/new'
    | '/sales-orders/$id'
    | '/transfers/$id'
    | '/transfers/new'
    | '/adjustments'
    | '/challans'
    | '/invoices'
    | '/items'
    | '/parties'
    | '/purchases'
    | '/receipts'
    | '/sales-orders'
    | '/transfers'
    | '/purchases/grn/$id'
    | '/purchases/grn/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/masters'
    | '/_authenticated/no-access'
    | '/_authenticated/numbering'
    | '/_authenticated/parties'
    | '/_authenticated/print-profiles'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/stock-ledger'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/adjustments/$id'
    | '/_authenticated/adjustments/new'
    | '/_authenticated/challans/$id'
    | '/_authenticated/challans/new'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/items/$id'
    | '/_authenticated/parties/$id'
    | '/_authenticated/purchases/$id'
    | '/_authenticated/purchases/new'
    | '/_authenticated/receipts/new'
    | '/_authenticated/sales-orders/$id'
    | '/_authenticated/transfers/$id'
    | '/_authenticated/transfers/new'
    | '/_authenticated/adjustments/'
    | '/_authenticated/challans/'
    | '/_authenticated/invoices/'
    | '/_authenticated/items/'
    | '/_authenticated/parties/'
    | '/_authenticated/purchases/'
    | '/_authenticated/receipts/'
    | '/_authenticated/sales-orders/'
    | '/_authenticated/transfers/'
    | '/_authenticated/purchases/grn/$id'
    | '/_authenticated/purchases/grn/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/no-access': {
      id: '/_authenticated/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthenticatedNoAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/numbering': {
      id: '/_authenticated/numbering'
      path: '/numbering'
      fullPath: '/numbering'
      preLoaderRoute: typeof AuthenticatedNumberingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parties': {
      id: '/_authenticated/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AuthenticatedPartiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print-profiles': {
      id: '/_authenticated/print-profiles'
      path: '/print-profiles'
      fullPath: '/print-profiles'
      preLoaderRoute: typeof AuthenticatedPrintProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock-ledger': {
      id: '/_authenticated/stock-ledger'
      path: '/stock-ledger'
      fullPath: '/stock-ledger'
      preLoaderRoute: typeof AuthenticatedStockLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adjustments/': {
      id: '/_authenticated/adjustments/'
      path: '/adjustments'
      fullPath: '/adjustments/'
      preLoaderRoute: typeof AuthenticatedAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adjustments/$id': {
      id: '/_authenticated/adjustments/$id'
      path: '/adjustments/$id'
      fullPath: '/adjustments/$id'
      preLoaderRoute: typeof AuthenticatedAdjustmentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adjustments/new': {
      id: '/_authenticated/adjustments/new'
      path: '/adjustments/new'
      fullPath: '/adjustments/new'
      preLoaderRoute: typeof AuthenticatedAdjustmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challans/': {
      id: '/_authenticated/challans/'
      path: '/challans'
      fullPath: '/challans/'
      preLoaderRoute: typeof AuthenticatedChallansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challans/$id': {
      id: '/_authenticated/challans/$id'
      path: '/challans/$id'
      fullPath: '/challans/$id'
      preLoaderRoute: typeof AuthenticatedChallansIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challans/new': {
      id: '/_authenticated/challans/new'
      path: '/challans/new'
      fullPath: '/challans/new'
      preLoaderRoute: typeof AuthenticatedChallansNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$id': {
      id: '/_authenticated/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthenticatedItemsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parties/': {
      id: '/_authenticated/parties/'
      path: '/'
      fullPath: '/parties/'
      preLoaderRoute: typeof AuthenticatedPartiesIndexRouteImport
      parentRoute: typeof AuthenticatedPartiesRoute
    }
    '/_authenticated/parties/$id': {
      id: '/_authenticated/parties/$id'
      path: '/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof AuthenticatedPartiesIdRouteImport
      parentRoute: typeof AuthenticatedPartiesRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/$id': {
      id: '/_authenticated/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AuthenticatedPurchasesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/new': {
      id: '/_authenticated/receipts/new'
      path: '/receipts/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof AuthenticatedReceiptsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-orders/': {
      id: '/_authenticated/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-orders/$id': {
      id: '/_authenticated/sales-orders/$id'
      path: '/sales-orders/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers/': {
      id: '/_authenticated/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AuthenticatedTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers/$id': {
      id: '/_authenticated/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof AuthenticatedTransfersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers/new': {
      id: '/_authenticated/transfers/new'
      path: '/transfers/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof AuthenticatedTransfersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/grn/$id': {
      id: '/_authenticated/purchases/grn/$id'
      path: '/purchases/grn/$id'
      fullPath: '/purchases/grn/$id'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/grn/new': {
      id: '/_authenticated/purchases/grn/new'
      path: '/purchases/grn/new'
      fullPath: '/purchases/grn/new'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPartiesRouteChildren {
  AuthenticatedPartiesIdRoute: typeof AuthenticatedPartiesIdRoute
  AuthenticatedPartiesIndexRoute: typeof AuthenticatedPartiesIndexRoute
}

const AuthenticatedPartiesRouteChildren: AuthenticatedPartiesRouteChildren = {
  AuthenticatedPartiesIdRoute: AuthenticatedPartiesIdRoute,
  AuthenticatedPartiesIndexRoute: AuthenticatedPartiesIndexRoute,
}

const AuthenticatedPartiesRouteWithChildren =
  AuthenticatedPartiesRoute._addFileChildren(AuthenticatedPartiesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedNoAccessRoute: typeof AuthenticatedNoAccessRoute
  AuthenticatedNumberingRoute: typeof AuthenticatedNumberingRoute
  AuthenticatedPartiesRoute: typeof AuthenticatedPartiesRouteWithChildren
  AuthenticatedPrintProfilesRoute: typeof AuthenticatedPrintProfilesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockLedgerRoute: typeof AuthenticatedStockLedgerRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedAdjustmentsIdRoute: typeof AuthenticatedAdjustmentsIdRoute
  AuthenticatedAdjustmentsNewRoute: typeof AuthenticatedAdjustmentsNewRoute
  AuthenticatedChallansIdRoute: typeof AuthenticatedChallansIdRoute
  AuthenticatedChallansNewRoute: typeof AuthenticatedChallansNewRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedItemsIdRoute: typeof AuthenticatedItemsIdRoute
  AuthenticatedPurchasesIdRoute: typeof AuthenticatedPurchasesIdRoute
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
  AuthenticatedReceiptsNewRoute: typeof AuthenticatedReceiptsNewRoute
  AuthenticatedSalesOrdersIdRoute: typeof AuthenticatedSalesOrdersIdRoute
  AuthenticatedTransfersIdRoute: typeof AuthenticatedTransfersIdRoute
  AuthenticatedTransfersNewRoute: typeof AuthenticatedTransfersNewRoute
  AuthenticatedAdjustmentsIndexRoute: typeof AuthenticatedAdjustmentsIndexRoute
  AuthenticatedChallansIndexRoute: typeof AuthenticatedChallansIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
  AuthenticatedSalesOrdersIndexRoute: typeof AuthenticatedSalesOrdersIndexRoute
  AuthenticatedTransfersIndexRoute: typeof AuthenticatedTransfersIndexRoute
  AuthenticatedPurchasesGrnIdRoute: typeof AuthenticatedPurchasesGrnIdRoute
  AuthenticatedPurchasesGrnNewRoute: typeof AuthenticatedPurchasesGrnNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedNoAccessRoute: AuthenticatedNoAccessRoute,
  AuthenticatedNumberingRoute: AuthenticatedNumberingRoute,
  AuthenticatedPartiesRoute: AuthenticatedPartiesRouteWithChildren,
  AuthenticatedPrintProfilesRoute: AuthenticatedPrintProfilesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockLedgerRoute: AuthenticatedStockLedgerRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedAdjustmentsIdRoute: AuthenticatedAdjustmentsIdRoute,
  AuthenticatedAdjustmentsNewRoute: AuthenticatedAdjustmentsNewRoute,
  AuthenticatedChallansIdRoute: AuthenticatedChallansIdRoute,
  AuthenticatedChallansNewRoute: AuthenticatedChallansNewRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedItemsIdRoute: AuthenticatedItemsIdRoute,
  AuthenticatedPurchasesIdRoute: AuthenticatedPurchasesIdRoute,
  AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  AuthenticatedReceiptsNewRoute: AuthenticatedReceiptsNewRoute,
  AuthenticatedSalesOrdersIdRoute: AuthenticatedSalesOrdersIdRoute,
  AuthenticatedTransfersIdRoute: AuthenticatedTransfersIdRoute,
  AuthenticatedTransfersNewRoute: AuthenticatedTransfersNewRoute,
  AuthenticatedAdjustmentsIndexRoute: AuthenticatedAdjustmentsIndexRoute,
  AuthenticatedChallansIndexRoute: AuthenticatedChallansIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
  AuthenticatedSalesOrdersIndexRoute: AuthenticatedSalesOrdersIndexRoute,
  AuthenticatedTransfersIndexRoute: AuthenticatedTransfersIndexRoute,
  AuthenticatedPurchasesGrnIdRoute: AuthenticatedPurchasesGrnIdRoute,
  AuthenticatedPurchasesGrnNewRoute: AuthenticatedPurchasesGrnNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
