/**
 * Copies the business-rule modules from the frontend (src/lib, src/api/types.ts)
 * into backend/src/shared so the API applies exactly the same GST, stock,
 * numbering and permission rules as the screens. Run after changing a rule:
 *   node scripts/sync-shared.mjs
 * The copies are committed so the server folder deploys on its own.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "backend/src/shared");
mkdirSync(out, { recursive: true });
const files = {
  "types.ts": "src/api/types.ts",
  "gst.ts": "src/lib/gst.ts",
  "stock.ts": "src/lib/stock.ts",
  "stock-rules.ts": "src/lib/stock-rules.ts",
  "dashboard-rules.ts": "src/lib/dashboard-rules.ts",
  "item-list-rules.ts": "src/lib/item-list-rules.ts",
  "item-detail-rules.ts": "src/lib/item-detail-rules.ts",
  "master-rules.ts": "src/lib/master-rules.ts",
  "godown-rules.ts": "src/lib/godown-rules.ts",
  "party-rules.ts": "src/lib/party-rules.ts",
  "sales-order-rules.ts": "src/lib/sales-order-rules.ts",
  "challan-rules.ts": "src/lib/challan-rules.ts",
  "invoice-rules.ts": "src/lib/invoice-rules.ts",
  "receipt-rules.ts": "src/lib/receipt-rules.ts",
  "purchase-rules.ts": "src/lib/purchase-rules.ts",
  "grn-rules.ts": "src/lib/grn-rules.ts",
  "transfer-rules.ts": "src/lib/transfer-rules.ts",
  "adjustment-rules.ts": "src/lib/adjustment-rules.ts",
  "numbering.ts": "src/lib/numbering.ts",
  "admin-rules.ts": "src/lib/admin-rules.ts",
  "reports.ts": "src/lib/reports.ts",
  "print-rules.ts": "src/lib/print-rules.ts",
  "search-rules.ts": "src/lib/search-rules.ts",
  "permissions.ts": "src/lib/permissions.ts",
  "import-parse.ts": "src/lib/import-parse.ts",
};
for (const [name, src] of Object.entries(files)) {
  let s = readFileSync(join(root, src), "utf8");
  s = s.replace(/from "@\/api\/types"/g, 'from "./types.js"').replace(/from "@\/lib\/([\w-]+)"/g, 'from "./$1.js"').replace(/from "\.\/([\w-]+)(?:\.ts)?"/g, 'from "./$1.js"');
  writeFileSync(join(out, name), `// GENERATED by server/scripts/sync-shared.mjs from ${src}. Do not edit here.\n${s}`);
}
console.log("synced", Object.keys(files).length, "files");
